version: 2.1

orbs:
  vfcommon: voiceflow/common@0.0.54
  validate-title: qventus/validate-title@0.0.4

jobs:
  build-and-test:
    executor: vfcommon/default-executor
    steps:
      - checkout
      - vfcommon/install_node_modules
      - vfcommon/lint_source
      - vfcommon/dependency_tests:
          step_name: Dependency Tests

workflows:

  pr-checker:
    jobs:
      - validate-title/validate:
          context: dev-test
          regex: >-
            $PR_REGEX
          filters:
            branches:
              ignore:
                - /env-.*/
                - staging
                - master

  test-and-release:
    jobs:
      - build-and-test:
          context: dev-test
      - vfcommon/release:
          context: dev-test
          requires:
            - build-and-test
          filters:
            branches:
              only: master
